image: ghcr.io/darkrain-nl/addon-s0pcm_reader
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.14-alpine3.24@sha256:6ea2adb735fd7121e43ef9f5401caac06266b9a73afecebaf600d21d7b5b23bc
  amd64: ghcr.io/home-assistant/amd64-base-python:3.14-alpine3.24@sha256:f59ecbbc63f781bf1215dd6b70f890a0487ff434ffc0fa721b368a5f4613d176
labels:
  io.hass.type: addon
  org.opencontainers.image.title: "S0PCM Reader"
  org.opencontainers.image.description: "S0PCM reader based on docker-s0pcm-reader"
  org.opencontainers.image.source: "https://github.com/darkrain-nl/home-assistant-addon-s0pcm-reader"
  org.opencontainers.image.authors: "darkrain-nl"
  org.opencontainers.image.url: "https://github.com/darkrain-nl/home-assistant-addon-s0pcm-reader"
  org.opencontainers.image.documentation: "https://github.com/darkrain-nl/home-assistant-addon-s0pcm-reader/blob/main/DOCS.md"
  org.opencontainers.image.licenses: "Apache-2.0"

cosign:
  identity: "https://github.com/darkrain-nl/home-assistant-addon-s0pcm-reader/.github/workflows/publish.yml@.*"
  base_identity: "https://github.com/home-assistant/docker-base/.*"
