# 3.14-alpine
FROM python:3.14-alpine@sha256:f6a589d43c42b9e7f7dc67a12d37132491f362859a5d750607710cc56da3bc72

LABEL org.opencontainers.image.title="S0PCM Reader (Standalone)" \
      org.opencontainers.image.description="Standalone S0PCM reader for non-Home Assistant environments" \
      org.opencontainers.image.source="https://github.com/darkrain-nl/home-assistant-addon-s0pcm-reader" \
      org.opencontainers.image.authors="darkrain-nl" \
      org.opencontainers.image.licenses="Apache-2.0"

WORKDIR /

COPY pyproject.toml uv.lock /tmp/uv/
COPY rootfs /

COPY --from=ghcr.io/astral-sh/uv:0.12.23@sha256:61d393e44e249f2e4b526b6c7ddcecce245946826e608e11c93ad4f5bba55b21 /uv /uvx /bin/

RUN --mount=type=cache,target=/root/.cache/uv \
    cd /tmp/uv && uv export --frozen --no-dev --no-emit-project --no-hashes | \
    uv pip install --link-mode=copy --system -r - && \
    cd / && rm -rf /tmp/uv

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python3 /usr/src/healthcheck.py || exit 1

CMD [ "python3", "/usr/src/s0pcm_reader.py" ]
