# 3.14-alpine
FROM python:3.14-alpine@sha256:9e9fde4d32eedce0b661d9ab91e826b62dddf28e928c230ec55f1866cac66b01

LABEL org.opencontainers.image.title="S0PCM Reader (Standalone)" \
      org.opencontainers.image.description="Standalone S0PCM reader for non-Home Assistant environments" \
      org.opencontainers.image.source="https://github.com/darkrain-nl/home-assistant-addon-s0pcm-reader" \
      org.opencontainers.image.authors="darkrain-nl" \
      org.opencontainers.image.licenses="Apache-2.0"

WORKDIR /

COPY pyproject.toml uv.lock /tmp/uv/
COPY rootfs /

COPY --from=ghcr.io/astral-sh/uv:0.12.22@sha256:f513a91fc62fe7c17567eee97230dd198e43edb8a9fbecca843714a4358fe1bc /uv /uvx /bin/

RUN --mount=type=cache,target=/root/.cache/uv \
    cd /tmp/uv && uv export --frozen --no-dev --no-emit-project --no-hashes | \
    uv pip install --link-mode=copy --system -r - && \
    cd / && rm -rf /tmp/uv

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python3 /usr/src/healthcheck.py || exit 1

CMD [ "python3", "/usr/src/s0pcm_reader.py" ]
