# 3.14-alpine
FROM python:3.14-alpine@sha256:dd4d2bd5b53d9b25a51da13addf2be586beebd5387e289e798e4083d94ca837a
COPY tests/standalone/simulator/simulator.py /simulator.py
CMD ["python3", "-u", "/simulator.py"]
